### ISSUE TITLE
Please release under the MIT license

### ISSUE THREAD

**Issue by shaypal5** [pyvista/numpydoc-validation#3]
Hey,

I'm wrapping this in a CLI tool, and would like to release this open-source-ly.

If you would like to see contributions and maintenance coming from the open source Python community, please release this under an open source license (I enthusiastically recomment MIT).

Cheers,
Shay

**Comment by akaszynski** [comment]
Done in https://github.com/pyvista/numpydoc-validation/commit/7303e7b7cd5d7cf10aad68bf6f8135739a1157b0, should have added that a while ago.

**Comment by akaszynski** [comment]
Also, I'd love to be able to resolve #2 by your CLI tool. Please let me know when you release that so I can include part of it here, or you can feel free to submit a PR (and I'll add CI).

**Comment by shaypal5** [comment]
Great, thank you!

I wish I could find time for either a PR or wrapping this up, but because your code ended up not working for me I've ended up writing a quick script for my own use:
https://github.com/pdpipe/pdpipe/blob/master/dev/scripts/numpydoc_validate.py
